package com.ruyicai.charge.dto;

import java.util.Date;

public class Tdnabind {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.ID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.MOBILEID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private String mobileid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.NAME
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.BANKCARDNO
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private String bankcardno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.CERTID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private String certid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.BANKADDRESS
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private String bankaddress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.CERTIDADDRESS
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private String certidaddress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.BINDTIME
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private Date bindtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column JRTSCH.TDNABIND.STATE
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    private Integer state;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.ID
     *
     * @return the value of JRTSCH.TDNABIND.ID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.ID
     *
     * @param ID the value for JRTSCH.TDNABIND.ID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setId(String id) {
        this.id = id == null ? null : (id.trim().equals("")? null: id.trim());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.MOBILEID
     *
     * @return the value of JRTSCH.TDNABIND.MOBILEID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public String getMobileid() {
        return mobileid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.MOBILEID
     *
     * @param MOBILEID the value for JRTSCH.TDNABIND.MOBILEID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setMobileid(String mobileid) {
        this.mobileid = mobileid == null ? null : (mobileid.trim().equals("")? null: mobileid.trim());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.NAME
     *
     * @return the value of JRTSCH.TDNABIND.NAME
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.NAME
     *
     * @param NAME the value for JRTSCH.TDNABIND.NAME
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setName(String name) {
        this.name = name == null ? null : (name.trim().equals("")? null: name.trim());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.BANKCARDNO
     *
     * @return the value of JRTSCH.TDNABIND.BANKCARDNO
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public String getBankcardno() {
        return bankcardno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.BANKCARDNO
     *
     * @param BANKCARDNO the value for JRTSCH.TDNABIND.BANKCARDNO
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setBankcardno(String bankcardno) {
        this.bankcardno = bankcardno == null ? null : (bankcardno.trim().equals("")? null: bankcardno.trim());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.CERTID
     *
     * @return the value of JRTSCH.TDNABIND.CERTID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public String getCertid() {
        return certid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.CERTID
     *
     * @param CERTID the value for JRTSCH.TDNABIND.CERTID
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setCertid(String certid) {
        this.certid = certid == null ? null : (certid.trim().equals("")? null: certid.trim());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.BANKADDRESS
     *
     * @return the value of JRTSCH.TDNABIND.BANKADDRESS
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public String getBankaddress() {
        return bankaddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.BANKADDRESS
     *
     * @param BANKADDRESS the value for JRTSCH.TDNABIND.BANKADDRESS
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setBankaddress(String Bankaddress) {
        this.bankaddress = bankaddress == null ? null : (bankaddress.trim().equals("")? null: bankaddress.trim());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.CERTIDADDRESS
     *
     * @return the value of JRTSCH.TDNABIND.CERTIDADDRESS
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public String getCertidaddress() {
        return certidaddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.CERTIDADDRESS
     *
     * @param CERTIDADDRESS the value for JRTSCH.TDNABIND.CERTIDADDRESS
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setCertidaddress(String certidaddress) {
        this.certidaddress = certidaddress == null ? null : (certidaddress.trim().equals("")? null: certidaddress.trim());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.BINDTIME
     *
     * @return the value of JRTSCH.TDNABIND.BINDTIME
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public Date getBindtime() {
        return bindtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.BINDTIME
     *
     * @param BINDTIME the value for JRTSCH.TDNABIND.BINDTIME
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setBindtime(Date bindtime) {
        this.bindtime = bindtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column JRTSCH.TDNABIND.STATE
     *
     * @return the value of JRTSCH.TDNABIND.STATE
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column JRTSCH.TDNABIND.STATE
     *
     * @param STATE the value for JRTSCH.TDNABIND.STATE
     *
     * @ibatorgenerated Thu Apr 15 11:22:52 CST 2010
     */
    public void setState(Integer state) {
        this.state = state;
    }
}