// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import com.ruyicai.charge.domain.Chargeconfig;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Chargeconfig_Roo_Entity {
    
    declare @type: Chargeconfig: @Entity;
    
    declare @type: Chargeconfig: @Table(name = "CHARGECONFIG");
    
    @PersistenceContext(unitName = "persistenceUnitMysql")
    transient EntityManager Chargeconfig.entityManager;
    
    @Transactional("transactionManagerMysql")
    public void Chargeconfig.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional("transactionManagerMysql")
    public void Chargeconfig.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Chargeconfig attached = Chargeconfig.findChargeconfig(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional("transactionManagerMysql")
    public void Chargeconfig.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional("transactionManagerMysql")
    public void Chargeconfig.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional("transactionManagerMysql")
    public Chargeconfig Chargeconfig.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Chargeconfig merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Chargeconfig.entityManager() {
        EntityManager em = new Chargeconfig().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Chargeconfig.countChargeconfigs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Chargeconfig o", Long.class).getSingleResult();
    }
    
    public static List<Chargeconfig> Chargeconfig.findAllChargeconfigs() {
        return entityManager().createQuery("SELECT o FROM Chargeconfig o", Chargeconfig.class).getResultList();
    }
    
    public static Chargeconfig Chargeconfig.findChargeconfig(String id) {
        if (id == null || id.length() == 0) return null;
        return entityManager().find(Chargeconfig.class, id);
    }
    
    public static List<Chargeconfig> Chargeconfig.findChargeconfigEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Chargeconfig o", Chargeconfig.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
