// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;

privileged aspect Dnapay_Roo_ToString {
    
    public String Dnapay.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Amt: ").append(getAmt()).append(", ");
        sb.append("Chargetime: ").append(getChargetime()).append(", ");
        sb.append("Memo: ").append(getMemo()).append(", ");
        sb.append("Mobileid: ").append(getMobileid()).append(", ");
        sb.append("Notifytime: ").append(getNotifytime()).append(", ");
        sb.append("Retcode: ").append(getRetcode()).append(", ");
        sb.append("Retmemo: ").append(getRetmemo()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Transactionid: ").append(getTransactionid()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
