// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;
import java.util.Date;

privileged aspect Nineteenpay_Roo_JavaBean {
    
    public String Nineteenpay.getTransactionid() {
        return this.transactionid;
    }
    
    public void Nineteenpay.setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }
    
    public String Nineteenpay.getUserno() {
        return this.userno;
    }
    
    public void Nineteenpay.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String Nineteenpay.getCardno() {
        return this.cardno;
    }
    
    public void Nineteenpay.setCardno(String cardno) {
        this.cardno = cardno;
    }
    
    public String Nineteenpay.getCardpwd() {
        return this.cardpwd;
    }
    
    public void Nineteenpay.setCardpwd(String cardpwd) {
        this.cardpwd = cardpwd;
    }
    
    public String Nineteenpay.getAmt() {
        return this.amt;
    }
    
    public void Nineteenpay.setAmt(String amt) {
        this.amt = amt;
    }
    
    public String Nineteenpay.getTotalamt() {
        return this.totalamt;
    }
    
    public void Nineteenpay.setTotalamt(String totalamt) {
        this.totalamt = totalamt;
    }
    
    public String Nineteenpay.getBalance() {
        return this.balance;
    }
    
    public void Nineteenpay.setBalance(String balance) {
        this.balance = balance;
    }
    
    public String Nineteenpay.getCardtype() {
        return this.cardtype;
    }
    
    public void Nineteenpay.setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }
    
    public Date Nineteenpay.getChargetime() {
        return this.chargetime;
    }
    
    public void Nineteenpay.setChargetime(Date chargetime) {
        this.chargetime = chargetime;
    }
    
    public Date Nineteenpay.getNotifytime() {
        return this.notifytime;
    }
    
    public void Nineteenpay.setNotifytime(Date notifytime) {
        this.notifytime = notifytime;
    }
    
    public String Nineteenpay.getState() {
        return this.state;
    }
    
    public void Nineteenpay.setState(String state) {
        this.state = state;
    }
    
    public String Nineteenpay.getRetcode() {
        return this.retcode;
    }
    
    public void Nineteenpay.setRetcode(String retcode) {
        this.retcode = retcode;
    }
    
    public String Nineteenpay.getRetmemo() {
        return this.retmemo;
    }
    
    public void Nineteenpay.setRetmemo(String retmemo) {
        this.retmemo = retmemo;
    }
    
    public String Nineteenpay.getMemo() {
        return this.memo;
    }
    
    public void Nineteenpay.setMemo(String memo) {
        this.memo = memo;
    }
    
}
