// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Taccount_Roo_JavaBean {
    
    public String Taccount.getUserno() {
        return this.userno;
    }
    
    public void Taccount.setUserno(String userno) {
        this.userno = userno;
    }
    
    public BigDecimal Taccount.getBalance() {
        return this.balance;
    }
    
    public void Taccount.setBalance(BigDecimal balance) {
        this.balance = balance;
    }
    
    public BigDecimal Taccount.getDrawbalance() {
        return this.drawbalance;
    }
    
    public void Taccount.setDrawbalance(BigDecimal drawbalance) {
        this.drawbalance = drawbalance;
    }
    
    public BigDecimal Taccount.getLastbetamt() {
        return this.lastbetamt;
    }
    
    public void Taccount.setLastbetamt(BigDecimal lastbetamt) {
        this.lastbetamt = lastbetamt;
    }
    
    public Date Taccount.getLastbettime() {
        return this.lastbettime;
    }
    
    public void Taccount.setLastbettime(Date lastbettime) {
        this.lastbettime = lastbettime;
    }
    
    public BigDecimal Taccount.getTotalbetamt() {
        return this.totalbetamt;
    }
    
    public void Taccount.setTotalbetamt(BigDecimal totalbetamt) {
        this.totalbetamt = totalbetamt;
    }
    
    public BigDecimal Taccount.getLastprizeamt() {
        return this.lastprizeamt;
    }
    
    public void Taccount.setLastprizeamt(BigDecimal lastprizeamt) {
        this.lastprizeamt = lastprizeamt;
    }
    
    public Date Taccount.getLastprizetime() {
        return this.lastprizetime;
    }
    
    public void Taccount.setLastprizetime(Date lastprizetime) {
        this.lastprizetime = lastprizetime;
    }
    
    public BigDecimal Taccount.getTotalprizeamt() {
        return this.totalprizeamt;
    }
    
    public void Taccount.setTotalprizeamt(BigDecimal totalprizeamt) {
        this.totalprizeamt = totalprizeamt;
    }
    
    public BigDecimal Taccount.getLastdepositamt() {
        return this.lastdepositamt;
    }
    
    public void Taccount.setLastdepositamt(BigDecimal lastdepositamt) {
        this.lastdepositamt = lastdepositamt;
    }
    
    public Date Taccount.getLastdeposittime() {
        return this.lastdeposittime;
    }
    
    public void Taccount.setLastdeposittime(Date lastdeposittime) {
        this.lastdeposittime = lastdeposittime;
    }
    
    public BigDecimal Taccount.getTotaldepositamt() {
        return this.totaldepositamt;
    }
    
    public void Taccount.setTotaldepositamt(BigDecimal totaldepositamt) {
        this.totaldepositamt = totaldepositamt;
    }
    
    public BigDecimal Taccount.getLastdrawamt() {
        return this.lastdrawamt;
    }
    
    public void Taccount.setLastdrawamt(BigDecimal lastdrawamt) {
        this.lastdrawamt = lastdrawamt;
    }
    
    public Date Taccount.getLastdrawtime() {
        return this.lastdrawtime;
    }
    
    public void Taccount.setLastdrawtime(Date lastdrawtime) {
        this.lastdrawtime = lastdrawtime;
    }
    
    public BigDecimal Taccount.getTotaldrawamt() {
        return this.totaldrawamt;
    }
    
    public void Taccount.setTotaldrawamt(BigDecimal totaldrawamt) {
        this.totaldrawamt = totaldrawamt;
    }
    
    public String Taccount.getMac() {
        return this.mac;
    }
    
    public void Taccount.setMac(String mac) {
        this.mac = mac;
    }
    
    public BigDecimal Taccount.getFreezebalance() {
        return this.freezebalance;
    }
    
    public void Taccount.setFreezebalance(BigDecimal freezebalance) {
        this.freezebalance = freezebalance;
    }
    
}
