// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;

privileged aspect Taccount_Roo_ToString {
    
    public String Taccount.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Balance: ").append(getBalance()).append(", ");
        sb.append("Drawbalance: ").append(getDrawbalance()).append(", ");
        sb.append("Freezebalance: ").append(getFreezebalance()).append(", ");
        sb.append("Lastbetamt: ").append(getLastbetamt()).append(", ");
        sb.append("Lastbettime: ").append(getLastbettime()).append(", ");
        sb.append("Lastdepositamt: ").append(getLastdepositamt()).append(", ");
        sb.append("Lastdeposittime: ").append(getLastdeposittime()).append(", ");
        sb.append("Lastdrawamt: ").append(getLastdrawamt()).append(", ");
        sb.append("Lastdrawtime: ").append(getLastdrawtime()).append(", ");
        sb.append("Lastprizeamt: ").append(getLastprizeamt()).append(", ");
        sb.append("Lastprizetime: ").append(getLastprizetime()).append(", ");
        sb.append("Mac: ").append(getMac()).append(", ");
        sb.append("Totalbetamt: ").append(getTotalbetamt()).append(", ");
        sb.append("Totaldepositamt: ").append(getTotaldepositamt()).append(", ");
        sb.append("Totaldrawamt: ").append(getTotaldrawamt()).append(", ");
        sb.append("Totalprizeamt: ").append(getTotalprizeamt()).append(", ");
        sb.append("Userno: ").append(getUserno()).append(", ");
        sb.append("Valid: ").append(isValid());
        return sb.toString();
    }
    
}
