// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;

privileged aspect Taccountdetail_Roo_ToString {
    
    public String Taccountdetail.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Amt: ").append(getAmt()).append(", ");
        sb.append("Balance: ").append(getBalance()).append(", ");
        sb.append("Blsign: ").append(getBlsign()).append(", ");
        sb.append("Drawamt: ").append(getDrawamt()).append(", ");
        sb.append("Drawbalance: ").append(getDrawbalance()).append(", ");
        sb.append("Flowno: ").append(getFlowno()).append(", ");
        sb.append("Freezeamt: ").append(getFreezeamt()).append(", ");
        sb.append("Freezebalance: ").append(getFreezebalance()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Mac: ").append(getMac()).append(", ");
        sb.append("Memo: ").append(getMemo()).append(", ");
        sb.append("Mobileid: ").append(getMobileid()).append(", ");
        sb.append("Otherid: ").append(getOtherid()).append(", ");
        sb.append("Plattime: ").append(getPlattime()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Taccounttype: ").append(getTaccounttype()).append(", ");
        sb.append("Ttransactionid: ").append(getTtransactionid()).append(", ");
        sb.append("Ttransactiontype: ").append(getTtransactiontype()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
