// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;

privileged aspect Talibatchpay_Roo_ToString {
    
    public String Talibatchpay.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("BatchFee: ").append(getBatchFee()).append(", ");
        sb.append("BatchNum: ").append(getBatchNum()).append(", ");
        sb.append("DetailData: ").append(getDetailData()).append(", ");
        sb.append("FailDetails: ").append(getFailDetails()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("NotifyID: ").append(getNotifyID()).append(", ");
        sb.append("NotifyTime: ").append(getNotifyTime()).append(", ");
        sb.append("NotifyType: ").append(getNotifyType()).append(", ");
        sb.append("PayDate: ").append(getPayDate()).append(", ");
        sb.append("SignType: ").append(getSignType()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("SuccessDetails: ").append(getSuccessDetails());
        return sb.toString();
    }
    
}
