// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;

privileged aspect Tcardfrom_Roo_ToString {
    
    public String Tcardfrom.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Memo: ").append(getMemo()).append(", ");
        sb.append("Name: ").append(getName());
        return sb.toString();
    }
    
}
