// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;

privileged aspect Tcardsnstate_Roo_ToString {
    
    public String Tcardsnstate.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Beginno: ").append(getBeginno()).append(", ");
        sb.append("Endno: ").append(getEndno()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("State: ").append(getState());
        return sb.toString();
    }
    
}
