// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Tcardfrom_Roo_JavaBean {
    
    public BigDecimal Tcardfrom.getId() {
        return this.id;
    }
    
    public void Tcardfrom.setId(BigDecimal id) {
        this.id = id;
    }
    
    public String Tcardfrom.getName() {
        return this.name;
    }
    
    public void Tcardfrom.setName(String name) {
        this.name = name;
    }
    
    public String Tcardfrom.getMemo() {
        return this.memo;
    }
    
    public void Tcardfrom.setMemo(String memo) {
        this.memo = memo;
    }
    
}
