// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Tcard_Roo_JavaBean {
    
    public String Tcard.getId() {
        return this.id;
    }
    
    public void Tcard.setId(String id) {
        this.id = id;
    }
    
    public BigDecimal Tcard.getAmt() {
        return this.amt;
    }
    
    public void Tcard.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
    public BigDecimal Tcard.getType() {
        return this.type;
    }
    
    public void Tcard.setType(BigDecimal type) {
        this.type = type;
    }
    
    public BigDecimal Tcard.getCardfrom() {
        return this.cardfrom;
    }
    
    public void Tcard.setCardfrom(BigDecimal cardfrom) {
        this.cardfrom = cardfrom;
    }
    
    public String Tcard.getCardsn() {
        return this.cardsn;
    }
    
    public void Tcard.setCardsn(String cardsn) {
        this.cardsn = cardsn;
    }
    
    public BigDecimal Tcard.getState() {
        return this.state;
    }
    
    public void Tcard.setState(BigDecimal state) {
        this.state = state;
    }
    
    public Date Tcard.getStarttime() {
        return this.starttime;
    }
    
    public void Tcard.setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    
    public Date Tcard.getEndtime() {
        return this.endtime;
    }
    
    public void Tcard.setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    
    public String Tcard.getPassword() {
        return this.password;
    }
    
    public void Tcard.setPassword(String password) {
        this.password = password;
    }
    
    public String Tcard.getManager() {
        return this.manager;
    }
    
    public void Tcard.setManager(String manager) {
        this.manager = manager;
    }
    
    public String Tcard.getBatchno() {
        return this.batchno;
    }
    
    public void Tcard.setBatchno(String batchno) {
        this.batchno = batchno;
    }
    
    public String Tcard.getAgencyno() {
        return this.agencyno;
    }
    
    public void Tcard.setAgencyno(String agencyno) {
        this.agencyno = agencyno;
    }
    
    public Date Tcard.getSelltime() {
        return this.selltime;
    }
    
    public void Tcard.setSelltime(Date selltime) {
        this.selltime = selltime;
    }
    
    public String Tcard.getDecrptkey() {
        return this.decrptkey;
    }
    
    public void Tcard.setDecrptkey(String decrptkey) {
        this.decrptkey = decrptkey;
    }
    
    public String Tcard.getChannel() {
        return this.channel;
    }
    
    public void Tcard.setChannel(String channel) {
        this.channel = channel;
    }
    
}
