// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import com.ruyicai.charge.domain.Tcardbat;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tcardbat_Roo_Entity {
    
    declare @type: Tcardbat: @Entity;
    
    declare @type: Tcardbat: @Table(name = "Tcardbat", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tcardbat.entityManager;
    
    @Transactional("transactionManager")
    public void Tcardbat.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional("transactionManager")
    public void Tcardbat.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tcardbat attached = Tcardbat.findTcardbat(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional("transactionManager")
    public void Tcardbat.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional("transactionManager")
    public void Tcardbat.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional("transactionManager")
    public Tcardbat Tcardbat.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tcardbat merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tcardbat.entityManager() {
        EntityManager em = new Tcardbat().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tcardbat.countTcardbats() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tcardbat o", Long.class).getSingleResult();
    }
    
    public static List<Tcardbat> Tcardbat.findAllTcardbats() {
        return entityManager().createQuery("SELECT o FROM Tcardbat o", Tcardbat.class).getResultList();
    }
    
    public static Tcardbat Tcardbat.findTcardbat(String id) {
        if (id == null || id.length() == 0) return null;
        return entityManager().find(Tcardbat.class, id);
    }
    
    public static List<Tcardbat> Tcardbat.findTcardbatEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tcardbat o", Tcardbat.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
