// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import com.ruyicai.charge.domain.Tcashdetail;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Tcashdetail_Roo_Json {
    
    public String Tcashdetail.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Tcashdetail Tcashdetail.fromJsonToTcashdetail(String json) {
        return new JSONDeserializer<Tcashdetail>().use(null, Tcashdetail.class).deserialize(json);
    }
    
    public static String Tcashdetail.toJsonArray(Collection<Tcashdetail> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Tcashdetail> Tcashdetail.fromJsonArrayToTcashdetails(String json) {
        return new JSONDeserializer<List<Tcashdetail>>().use(null, ArrayList.class).use("values", Tcashdetail.class).deserialize(json);
    }
    
}
