// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import com.ruyicai.charge.domain.Tcashdetail;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tcashdetail_Roo_Entity {
    
    declare @type: Tcashdetail: @Entity;
    
    declare @type: Tcashdetail: @Table(name = "TCASHDETAIL", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tcashdetail.entityManager;
    
    @Transactional("transactionManager")
    public void Tcashdetail.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional("transactionManager")
    public void Tcashdetail.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tcashdetail attached = Tcashdetail.findTcashdetail(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional("transactionManager")
    public void Tcashdetail.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional("transactionManager")
    public void Tcashdetail.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional("transactionManager")
    public Tcashdetail Tcashdetail.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tcashdetail merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tcashdetail.entityManager() {
        EntityManager em = new Tcashdetail().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tcashdetail.countTcashdetails() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tcashdetail o", Long.class).getSingleResult();
    }
    
    public static List<Tcashdetail> Tcashdetail.findAllTcashdetails() {
        return entityManager().createQuery("SELECT o FROM Tcashdetail o", Tcashdetail.class).getResultList();
    }
    
    public static Tcashdetail Tcashdetail.findTcashdetail(String id) {
        if (id == null || id.length() == 0) return null;
        return entityManager().find(Tcashdetail.class, id);
    }
    
    public static List<Tcashdetail> Tcashdetail.findTcashdetailEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tcashdetail o", Tcashdetail.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
