// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Tchannelcard_Roo_JavaBean {
    
    public String Tchannelcard.getId() {
        return this.id;
    }
    
    public void Tchannelcard.setId(String id) {
        this.id = id;
    }
    
    public String Tchannelcard.getAgencyno() {
        return this.agencyno;
    }
    
    public void Tchannelcard.setAgencyno(String agencyno) {
        this.agencyno = agencyno;
    }
    
    public String Tchannelcard.getCardcode() {
        return this.cardcode;
    }
    
    public void Tchannelcard.setCardcode(String cardcode) {
        this.cardcode = cardcode;
    }
    
    public BigDecimal Tchannelcard.getCardamt() {
        return this.cardamt;
    }
    
    public void Tchannelcard.setCardamt(BigDecimal cardamt) {
        this.cardamt = cardamt;
    }
    
    public BigDecimal Tchannelcard.getCardcount() {
        return this.cardcount;
    }
    
    public void Tchannelcard.setCardcount(BigDecimal cardcount) {
        this.cardcount = cardcount;
    }
    
    public Date Tchannelcard.getGettime() {
        return this.gettime;
    }
    
    public void Tchannelcard.setGettime(Date gettime) {
        this.gettime = gettime;
    }
    
    public String Tchannelcard.getDecrptkey() {
        return this.decrptkey;
    }
    
    public void Tchannelcard.setDecrptkey(String decrptkey) {
        this.decrptkey = decrptkey;
    }
    
}
