// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;

privileged aspect Tchannelcard_Roo_ToString {
    
    public String Tchannelcard.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Agencyno: ").append(getAgencyno()).append(", ");
        sb.append("Cardamt: ").append(getCardamt()).append(", ");
        sb.append("Cardcode: ").append(getCardcode()).append(", ");
        sb.append("Cardcount: ").append(getCardcount()).append(", ");
        sb.append("Decrptkey: ").append(getDecrptkey()).append(", ");
        sb.append("Gettime: ").append(getGettime()).append(", ");
        sb.append("Id: ").append(getId());
        return sb.toString();
    }
    
}
