// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.Character;
import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Ttransaction_Roo_JavaBean {
    
    public BigDecimal Ttransaction.getType() {
        return this.type;
    }
    
    public void Ttransaction.setType(BigDecimal type) {
        this.type = type;
    }
    
    public String Ttransaction.getUserno() {
        return this.userno;
    }
    
    public void Ttransaction.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String Ttransaction.getAcceptno() {
        return this.acceptno;
    }
    
    public void Ttransaction.setAcceptno(String acceptno) {
        this.acceptno = acceptno;
    }
    
    public String Ttransaction.getFlowno() {
        return this.flowno;
    }
    
    public void Ttransaction.setFlowno(String flowno) {
        this.flowno = flowno;
    }
    
    public Date Ttransaction.getPlattime() {
        return this.plattime;
    }
    
    public void Ttransaction.setPlattime(Date plattime) {
        this.plattime = plattime;
    }
    
    public BigDecimal Ttransaction.getAmt() {
        return this.amt;
    }
    
    public void Ttransaction.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
    public BigDecimal Ttransaction.getFee() {
        return this.fee;
    }
    
    public void Ttransaction.setFee(BigDecimal fee) {
        this.fee = fee;
    }
    
    public String Ttransaction.getBankid() {
        return this.bankid;
    }
    
    public void Ttransaction.setBankid(String bankid) {
        this.bankid = bankid;
    }
    
    public String Ttransaction.getBankaccount() {
        return this.bankaccount;
    }
    
    public void Ttransaction.setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }
    
    public String Ttransaction.getBankorderid() {
        return this.bankorderid;
    }
    
    public void Ttransaction.setBankorderid(String bankorderid) {
        this.bankorderid = bankorderid;
    }
    
    public Date Ttransaction.getBankordertime() {
        return this.bankordertime;
    }
    
    public void Ttransaction.setBankordertime(Date bankordertime) {
        this.bankordertime = bankordertime;
    }
    
    public String Ttransaction.getBanktrace() {
        return this.banktrace;
    }
    
    public void Ttransaction.setBanktrace(String banktrace) {
        this.banktrace = banktrace;
    }
    
    public Date Ttransaction.getBankrettime() {
        return this.bankrettime;
    }
    
    public void Ttransaction.setBankrettime(Date bankrettime) {
        this.bankrettime = bankrettime;
    }
    
    public BigDecimal Ttransaction.getState() {
        return this.state;
    }
    
    public void Ttransaction.setState(BigDecimal state) {
        this.state = state;
    }
    
    public String Ttransaction.getRetcode() {
        return this.retcode;
    }
    
    public void Ttransaction.setRetcode(String retcode) {
        this.retcode = retcode;
    }
    
    public String Ttransaction.getRetmemo() {
        return this.retmemo;
    }
    
    public void Ttransaction.setRetmemo(String retmemo) {
        this.retmemo = retmemo;
    }
    
    public String Ttransaction.getMemo() {
        return this.memo;
    }
    
    public void Ttransaction.setMemo(String memo) {
        this.memo = memo;
    }
    
    public BigDecimal Ttransaction.getBankcheck() {
        return this.bankcheck;
    }
    
    public void Ttransaction.setBankcheck(BigDecimal bankcheck) {
        this.bankcheck = bankcheck;
    }
    
    public String Ttransaction.getPaytype() {
        return this.paytype;
    }
    
    public void Ttransaction.setPaytype(String paytype) {
        this.paytype = paytype;
    }
    
    public Character Ttransaction.getAccesstype() {
        return this.accesstype;
    }
    
    public void Ttransaction.setAccesstype(Character accesstype) {
        this.accesstype = accesstype;
    }
    
    public String Ttransaction.getChannel() {
        return this.channel;
    }
    
    public void Ttransaction.setChannel(String channel) {
        this.channel = channel;
    }
    
    public String Ttransaction.getSubchannel() {
        return this.subchannel;
    }
    
    public void Ttransaction.setSubchannel(String subchannel) {
        this.subchannel = subchannel;
    }
    
    public BigDecimal Ttransaction.getPresentamt() {
        return this.presentamt;
    }
    
    public void Ttransaction.setPresentamt(BigDecimal presentamt) {
        this.presentamt = presentamt;
    }
    
    public BigDecimal Ttransaction.getLadderpresentflag() {
        return this.ladderpresentflag;
    }
    
    public void Ttransaction.setLadderpresentflag(BigDecimal ladderpresentflag) {
        this.ladderpresentflag = ladderpresentflag;
    }
    
    public BigDecimal Ttransaction.getContinuebettype() {
        return this.continuebettype;
    }
    
    public void Ttransaction.setContinuebettype(BigDecimal continuebettype) {
        this.continuebettype = continuebettype;
    }
    
    public String Ttransaction.getOrderid() {
        return this.orderid;
    }
    
    public void Ttransaction.setOrderid(String orderid) {
        this.orderid = orderid;
    }
    
}
