// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Tusercard_Roo_JavaBean {
    
    public String Tusercard.getTtransactionid() {
        return this.ttransactionid;
    }
    
    public void Tusercard.setTtransactionid(String ttransactionid) {
        this.ttransactionid = ttransactionid;
    }
    
    public String Tusercard.getAgencyno() {
        return this.agencyno;
    }
    
    public void Tusercard.setAgencyno(String agencyno) {
        this.agencyno = agencyno;
    }
    
    public String Tusercard.getUserno() {
        return this.userno;
    }
    
    public void Tusercard.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String Tusercard.getTcardid() {
        return this.tcardid;
    }
    
    public void Tusercard.setTcardid(String tcardid) {
        this.tcardid = tcardid;
    }
    
    public BigDecimal Tusercard.getCardstate() {
        return this.cardstate;
    }
    
    public void Tusercard.setCardstate(BigDecimal cardstate) {
        this.cardstate = cardstate;
    }
    
    public Date Tusercard.getGettime() {
        return this.gettime;
    }
    
    public void Tusercard.setGettime(Date gettime) {
        this.gettime = gettime;
    }
    
}
