// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.charge.domain;

import java.lang.String;
import java.util.Date;

privileged aspect Dnapay_Roo_JavaBean {
    
    public String Dnapay.getTransactionid() {
        return this.transactionid;
    }
    
    public void Dnapay.setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }
    
    public String Dnapay.getUserno() {
        return this.userno;
    }
    
    public void Dnapay.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String Dnapay.getMobileid() {
        return this.mobileid;
    }
    
    public void Dnapay.setMobileid(String mobileid) {
        this.mobileid = mobileid;
    }
    
    public String Dnapay.getAmt() {
        return this.amt;
    }
    
    public void Dnapay.setAmt(String amt) {
        this.amt = amt;
    }
    
    public Date Dnapay.getChargetime() {
        return this.chargetime;
    }
    
    public void Dnapay.setChargetime(Date chargetime) {
        this.chargetime = chargetime;
    }
    
    public Date Dnapay.getNotifytime() {
        return this.notifytime;
    }
    
    public void Dnapay.setNotifytime(Date notifytime) {
        this.notifytime = notifytime;
    }
    
    public String Dnapay.getState() {
        return this.state;
    }
    
    public void Dnapay.setState(String state) {
        this.state = state;
    }
    
    public String Dnapay.getRetcode() {
        return this.retcode;
    }
    
    public void Dnapay.setRetcode(String retcode) {
        this.retcode = retcode;
    }
    
    public String Dnapay.getRetmemo() {
        return this.retmemo;
    }
    
    public void Dnapay.setRetmemo(String retmemo) {
        this.retmemo = retmemo;
    }
    
    public String Dnapay.getMemo() {
        return this.memo;
    }
    
    public void Dnapay.setMemo(String memo) {
        this.memo = memo;
    }
    
}
